### ISSUE TITLE
Underlaying layout lost size settings

### ISSUE THREAD

**Issue by avackova** [wolfie/PopupExtension#13]
I have a button, that opens window with popup button on click. The original layout losses 100% height when opening the window:
![full](https://f.cloud.github.com/assets/1171754/1520288/2b6c287e-4b78-11e3-94aa-876b6e761c9c.PNG)
![detail](https://f.cloud.github.com/assets/1171754/1520289/301ccaa4-4b78-11e3-9a7e-8ad38dc96986.PNG)

**Comment by wolfie** [comment]
How do you add the extension to your application? merely opening the popup shouldn't do that, but when you PopupExtension.extend() some component, you might get that kind of behavior.

Try to use PoupExtension.extendWithManualBundle() instead, and see if it works better.

**Comment by avackova** [comment]
Unfortunately, after replacing

```
        final PopupExtension itemExtension = PopupExtension.extend(item);
```

with  

```
        final PopupExtension itemExtension = PopupExtension.extendWithManualBundle(item).getPopupExtension();
```

the popup does't show at all.

I use the popup extension as a content of CustomField added to a Window.

**Comment by wolfie** [comment]
You need to add the data transfer component somewhere in your current layout for this to work. Please refer to the JavaDoc of extendWithManualBundle

**Comment by avackova** [comment]
Unfortunately javadoc is really parsimonious and there is no example, so I have no idea how to add the data transfer component somewhere in my current layout.

```
        FormLayout layout = new FormLayout();
        layout.setMargin(true);
        for(Field<?> field: fieldGroup.getFields()){
            layout.addComponent(field);
        }
        fieldGroup.setReadOnly(true);
        Button item = new Button(value == null ? "" : value.toString());
        item.setSizeFull();
        item.addStyleName(BaseTheme.BUTTON_LINK);
        final PopupExtension itemExtension = PopupExtension.extendWithManualBundle(item).getPopupExtension();
//      final PopupExtension itemExtension = PopupExtension.extend(item);
        item.addClickListener(new Button.ClickListener() {

            private static final long serialVersionUID = 5542774399062628287L;

            public void buttonClick(final ClickEvent event) {
                if (itemExtension.isOpen()) {
                    itemExtension.close();
                }else{
                    itemExtension.open();
                }
            }
        });
        itemExtension.setContent(new Panel(getCaption(), layout));
        itemExtension.setAnchor(Alignment.MIDDLE_RIGHT);
        itemExtension.setDirection(Alignment.MIDDLE_RIGHT);     
        return item;
```

**Comment by avackova** [comment]
Sorry, but I don't understand it.I've tried to modify _beforeClientResponse_ method:

```
    @Override
    public void beforeClientResponse(boolean initial) {
        super.beforeClientResponse(initial);
        if (initial) {
            ((AbstractComponentContainer) getParent()).addComponent(itemExtensionBundle.getDataTransferComponent());
        }
    }
```

, but then the fields are empty;
![empty](https://f.cloud.github.com/assets/1171754/1522980/27c5f708-4bb0-11e3-8859-be234b1c7dc7.PNG)

When using _PopupExtension.extend(item)_:
![ok](https://f.cloud.github.com/assets/1171754/1522960/ef70d22e-4baf-11e3-91c8-96466bdf08d2.PNG)

**Comment by wolfie** [comment]
The DataTransferComponent is an invisible component that you need to add to some layout (`layout.addComponent(dataTransferComponent)`) that's currently attached to your application.

I have a feeling that Vaadin's internal PopupView might work better for you, or the PopupButton found in the Directory. PopupExtension is experimental and quite the hack, and can lead to strange things like this.
