### ISSUE TITLE
why PopupExtensionConnector need to addVisibilityChangeListener?

### ISSUE THREAD

**Issue by soulaxin** [wolfie/PopupExtension#14]
com.github.wolfie.popupextension.client.PopupExtensionConnector
int init method
popup.addVisibilityChangeListener(this)

**Comment by wolfie** [comment]
It calls the `becameVisible` method that communicates the state changes back to the server via RPC.

I'd rather that the GitHub issues would be used to report issues in the code, rather than asking functional questions.

**Comment by soulaxin** [comment]
thank u for reply, i'm sorry for that.
this indeed is an issue for me.
a component focus event to show popup, blur event to hide popup.
when focus on a component to show popup, if i click other area of browser ，then click content of page，there is opportunity make an inifinite loop，the popup will dispear and display again and again.
thanks for your help
