### ISSUE TITLE
popup content gets lost on the client side

### ISSUE THREAD

**Issue by robaca** [wolfie/PopupExtension#8]
We use PopupExtension in an application, where the extended component is part of a persistent view. If we switch to another view and then switch back , the popup does not work any more, as the widget tree below the extension widget on the client side got lost.

**Comment by wolfie** [comment]
I'll take a look (at some point) and see if there's a way to fix this. The whole thing is a big (experimental) hack, so I wouldn't be surprised if this use case will remain unsupported until Vaadin supports sending Connectors over the wire as a property in a state.

**Comment by wolfie** [comment]
Found the bug: `PopupExtensionDataTransferComponentConnector` finds the `PopupExtensionWidget` it should send the popup contents to with the help of a globally accessible map. To avoid memory leaks, the map is cleaned up whenever a `PopupExtensionWidget` is detached. Unfortunately, as the `PopupExtensionWidget` is reattached, there's no signal for the `PopupExtensionDataTransferComponentConnector` to reinject the popup contents.

**Comment by wolfie** [comment]
Update to Directory coming soon
